import type { Metadata, Viewport } from 'next';
import { Inter, Playfair_Display } from 'next/font/google';
import '../globals.css';
import { Providers } from '../providers';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';

// Apple naprave dobijo pravo SF Pro prek -apple-system v --font-sans
// (app/globals.css); Inter je fallback za vse ostale platforme.
// latin-ext je obvezen — brez njega č/š/ž padeta na sistemsko pisavo.
const interUi = Inter({
  variable: '--font-ui',
  subsets: ['latin', 'latin-ext'],
  display: 'swap',
});

const playfair = Playfair_Display({
  variable: '--font-serif',
  subsets: ['latin', 'latin-ext'],
  weight: ['400', '500', '600'],
  display: 'swap',
});

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
};

const siteUrl = process.env.NEXT_PUBLIC_APP_URL;

export const metadata: Metadata = {
  // Favicons come from the file conventions app/icon.png, app/apple-icon.png
  // and app/favicon.ico — all generated by scripts/build-brand.mjs.
  ...(siteUrl ? { metadataBase: new URL(siteUrl) } : {}),
  title: 'Jedro+',
  description: 'Jedro+ - Sistem za upravljanje terminov',
  openGraph: {
    title: 'Jedro+',
    description: 'Jedro+ - Sistem za upravljanje terminov',
    siteName: 'Jedro+',
    type: 'website',
    images: [{ url: '/og-image.png', width: 1200, height: 630, alt: 'Jedro+' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Jedro+',
    description: 'Jedro+ - Sistem za upravljanje terminov',
    images: ['/og-image.png'],
  },
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as (typeof routing.locales)[number])) {
    notFound();
  }

  // ⭐ KEY FIX: enable next-intl locale context for RSC/getRequestConfig
  setRequestLocale(locale);

  const messages = await getMessages();

  return (
    <html lang={locale} className={interUi.variable}>
      <body className={`${playfair.variable} antialiased`}>
        <NextIntlClientProvider messages={messages} locale={locale}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
